application: secretsanta
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /style
  static_dir: style
  
- url: /.*
  script: secretsanta.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest